### ISSUE TITLE
Python - failed to import cudamat. Using npmat instead

### ISSUE THREAD

**Issue by deerdodo** [lizhongguo/dbn#1]
i am trying to build a deep belief network model, this is my code
```
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Dropout
from nolearn.dbn import DBN

##np.set_printoptions(threshold=np.inf, linewidth=np.inf) 

train = np.loadtxt("TrainDatasetFinal.txt", delimiter=",")
test = np.loadtxt("testDatasetFinal.txt", delimiter=",")

y_train = train[:,7]
y_test = test[:,7]

train_spec = train[:,6]
test_spec = test[:,6]

dbn_model = DBN([x_train.shape[1], 300, 10],
                learn_rates = 0.3,
                learn_rate_decays = 0.9,
                epochs = 10,
                verbose = 1)

dbn_model.fit(train_spec, y_train)
```
but it gets me the following error
```
Traceback (most recent call last):
  File "G:\dbn.py", line 4, in <module>
    from nolearn.dbn import DBN
  File "C:\Python36\lib\site-packages\nolearn\dbn.py", line 5, in <module>
    from gdbn.dbn import buildDBN
  File "C:\Python36\lib\site-packages\gdbn\dbn.py", line 25, in <module>
    import gnumpy as gnp
  File "C:\Python36\lib\site-packages\gnumpy.py", line 52
    except: print 'gnumpy: failed to import cudamat. Using npmat instead. No GPU will be used.'; _useGpu = 'no'
                                                                                              ^
SyntaxError: Missing parentheses in call to 'print'
```

Here is a sample from the dataset

(Patient Number, time in millisecond, accelerometer x-axis,y-axis, z-axis,magnitude, spectrogram,label (0 or 1))
```

1,15,70,39,-970,947321,596768455815000,0
1,31,70,39,-970,947321,612882670787000,0
1,46,60,49,-960,927601,602179976392000,0
1,62,60,49,-960,927601,808020878060000,0
1,78,50,39,-960,925621,726154800929000,0
```
in the dataset i am using the only the spectrogram as input feature and the label (0 or 1) as the output the total traing samples is 1,415,684

**Comment by lizhongguo** [comment]
First I am sorry so late to reply you . I am just a guy who begin to learn deep learning , maybe this issue can help you  [https://github.com/cudamat/cudamat/issues/90]
